### PR TITLE
Native JS Demo page redone + focus event emitter

### PR DESCRIPTION
**Pull request by rayzru**

### CODE REVIEW

**Comment by rayzru** [comment]
image
Demo page screenshot.

**Comment by oferh** [comment]
@rayzru thanks a lot for this!
will review it shortly

**Comment by oferh** [comment]
Can you also do some touchups on material demo?

**Comment by rayzru** [comment]
Yeah, i guess.
But maybe later :)

**Comment by oferh** [comment]
@rayzru would appreciate it if you can enhance it a bit, even the UI aspects of it!

I did my best when it comes to descriptions, but you are right an English native can probably easily improve it.

**Comment by rayzru** [comment]
Please update `gh-pages` branch.
You still got old one http://oferh.github.io/ng2-completer/#/native

**Comment by oferh** [comment]
haven't merged it to master yet, I want to add some more changes and only then release a version.

**Comment by oferh** [comment]
@rayzru would you like me to add you to the contributors list in package.json?

**Comment by rayzru** [comment]
idk, as you wish. It's all up to you.

**Comment by oferh** [comment]
you made a helpful contribution so I think it's appropriate, you can make a PR for it or just send me any of the following details: name, email, url

**Comment by rayzru** [comment]
Andrew Rumm <rayz@rayz.ru>

**Pull request merged**
