### PR TITLE
update for angular 9

### PR DESCRIPTION
**Pull request by riderx**

### CODE REVIEW

**Comment by koreem** [comment]
Waiting for this one as well.

**Comment by rvdleun** [comment]
I could use this update as well.

**Comment by giansalex** [comment]
Why change to `ngx-completer`?, this bring more work ...

**Comment by BobCashStory** [comment]
@giansalex i did this change to deploy it on npm

**Comment by giansalex** [comment]
@BobCashStory, when do you think deploy it on npm?

**Comment by szh** [comment]
@BobCashStory I'm trying to use your fork in a project but I'm getting errors whether I try to import from 'ngx-completer' or 'ng2-completer.

**Comment by nirgn975** [comment]
@oferh Any plans to add Angular 9 support?

**Comment by giansalex** [comment]
@oferh is not found.... :confused:

**Comment by oferh** [comment]
@riderx thanks for the PR - since there are a lot of name related changes I've handpicked changes for this PR and added angular9 support for the dev branch.

**Comment by HackPoint** [comment]
@oferh Hey so how to fix this issue, it's seems to be still having an issue with angular9
[https://github.com/akveo/ng2-smart-table/issues/1134](url)

**Comment by ofer-papaya** [comment]
@HackPoint are you using the `@next` version?

**Comment by riderx** [comment]
Any plan to release in prod ?

**Pull request closed without merging**
