### PR TITLE
Fix production builds

### PR DESCRIPTION
**Pull request by Chocobozzz**
1.2.1 breaks production builds 

<pre>Property 'ctrInput' is private and only accessible within class 'CompleterCmp'</pre>

### CODE REVIEW

**Comment by rangelke** [comment]
The issue might be caused by: https://github.com/oferh/ng2-completer/commit/33b366dd6c0d6469df85f8730d7d2e56df16e167
I wonder if reverting the renaming could fix the issue, since probably what happens is that ctrInput is a directive on the input and I added a private ElementRef. 

I don't know what would be the better solution, make the elementRef public or revert the renaming to not conflict with the directive?

**Comment by oferh** [comment]
I think that renaming the property is a better solution if it solves the problem

**Comment by Chocobozzz** [comment]
Do not hesitate to close this PR if you prefer to rename the property.

**Comment by oferh** [comment]
rename didn't work, it has probably something to do with the way the `@ViewChild` is working

**Pull request merged**
